// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkstbmnbjjgiomvgfzvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rc3RibW5iampnaW9tdmdmenZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NzkzMjUsImV4cCI6MjA1ODQ1NTMyNX0.Srh-SZ9u5R_22envUp6DRxMb1afgOZLXCua2J2IS6_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);